language: python
python:
- 3.4

#installation
  #befor install
  #install
install:
  - pip install -r requirements.txt

#script
  #before script
  #script
script: 
  - python3 test_fruits.py
  - mkdir ShortStory
  - cd ShortStory
  - touch KKK
  - echo 5
  
#after script
  #after success
  #after failure

#deploy
  #before deploy
  #deploy
  #after deploy

#safelist
branches:
  only:
  - master
  - /[utp][a-q]*[t]\b//
  
#blocklist
branches:
  exept:
  - opt
# comments
